models.py
from app import db
from sqlalchemy.orm import Mapped, mapped_column


class User(db.Model):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(db.Integer, primary_key=True)
    username: Mapped[str] = mapped_column(db.String(50), nullable=False, unique=True)
    password: Mapped[str] = mapped_column(db.String(250), nullable=False)

    def __repr__(self) -> str:
        return f"User(id={self.id!r}, username={self.username!r}, password={self.password!r})"

app.py
import os
import secrets
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from utils import get_postgres_database_uri


app = Flask(__name__)
db = SQLAlchemy()

if "SQL_DATABASE_TYPE" in os.environ and os.environ["SQL_DATABASE_TYPE"] == "postgres":
    app.config["SQLALCHEMY_DATABASE_URI"] = get_postgres_database_uri()
else:
    app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///project.db"

app.config["SECRET_KEY"] = secrets.token_hex()

db.init_app(app)

import models

with app.app_context():
    db.create_all()

import auth
app.register_blueprint(auth.bp)

import views
app.register_blueprint(views.bp)
app.add_url_rule('/', endpoint='index')

auth.py
from app import db
from flask import request, render_template, Blueprint, flash, redirect, url_for, session
from werkzeug.security import generate_password_hash, check_password_hash
from functools import wraps
from models import User


bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route("/register", methods=('GET', 'POST'))
def register():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        error = None

        if username and password:
            existing_user = db.session.execute(db.select(User).where(User.username == username)).first()
            if existing_user:
                error = f"Username {username} already exist"
            else: 
                user = User(
                    username = username,
                    password = generate_password_hash(password)
                )
                db.session.add(user)
                db.session.commit()
                return redirect(url_for('auth.login'))

        flash(error)

    return render_template('auth/register.html')
 

@bp.route("/login", methods=('GET', 'POST'))
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        error = None

        user = db.session.execute(db.select(User).where(User.username == username)).scalar_one_or_none()

        if user:
            if check_password_hash(user.password, password):
                session['username'] = username
                return redirect(url_for('views.success'))
            else:
                error = "Check your credentials"
        else:
            error = "User does not exist"

        flash(error)

    return render_template('auth/login.html')


@bp.route('/logout', methods=['GET', 'POST'])
def logout():
    session.pop('username', None)
    return redirect(url_for('index'))


def login_required(func):
    @wraps(func)
    def decorated_view(*args, **kwargs):
        if not "username" in session.keys():
            return redirect(url_for('index'))
        return func(*args, **kwargs)

    return decorated_view

views.py
from flask import Blueprint, render_template
from auth import login_required

bp = Blueprint('views', __name__)


@bp.route('/')
def index():
    return render_template('index.html')


@bp.route('/success', methods=['GET', 'POST'])
@login_required
def success():
    return render_template('success.html')

templates/base.html
<!doctype html>
<title>{% block title %}{% endblock %}</title>
<!-- <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}"> -->
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
<div class="container mt-3">
  <header>
    {% block header %}{% endblock %}
  </header>
  {% with messages = get_flashed_messages() %}
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-warning alert-dismissible fade show">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      {% endfor %}
    {% endif %}
  {% endwith %}
  {% block content %}{% endblock %}
</div>

templates/index.html
{% extends "base.html" %}
{% block title %}Home Page{% endblock %}
{% block content %}
    <h1>Login Authentication System in Flask</h1>
    <a href="{{ url_for('auth.login') }}">Login Page</a><br>
    <a href="{{ url_for('auth.register') }}">Register Page</a><br>
{% endblock %}

templates/success.html
{% extends "base.html" %}
{% block title %}Success Page{% endblock %}
{% block content %}
{% if g.user %}
<h1>Hello, {{ g.user['username'] }}</h1>
{% endif %}
<img src="{{ url_for('static', filename='uareamazing.jpg') }}" class="img-fluid" alt="uareamazing.jpg">
<div class="mt-3"></div>
<a href="{{ url_for('auth.logout') }}">Press here to logout</a>
</div>
{% endblock %}